#!/usr/bin/env python3
"""Fetch, trim and embed the real drum loops for the displayer's practice player.

Each LOOPS entry names a CC0 recording (a freesound HQ preview URL), the bar
window to keep and its musical metadata. The script downloads the source into a
temp cache, decodes it with ffmpeg, cuts the window on exact bar boundaries,
wrap-crossfades the seam (the audio right after the cut end is blended into the
segment head, so the loop point continues naturally), encodes OGG Vorbis and
writes everything base64-embedded to data/brush_loops.js — a <script>-loadable
bundle, since fetch() is unavailable on file://.

The player (brushes.js) rate-stretches a loop to the chosen tempo and restarts
it at every form top, so chart alignment never drifts.

Requires ffmpeg on PATH. Deterministic given the same source downloads.

Usage:  python apps/displayer/embed_brush_loops.py
"""

from __future__ import annotations

import base64
import io
import subprocess
import tempfile
import wave
from pathlib import Path

import numpy as np

SR = 44100
OUT = Path(__file__).resolve().parent / "data" / "brush_loops.js"
CACHE = Path(tempfile.gettempdir()) / "grilles_brush_loops"

# One loop per meter (beats_per_bar). start_bar/bars select the kept window
# (0-based bars from the source's downbeat, which freesound previews put at 0).
LOOPS = [
    {
        "title": "Jazz Drum Loop – Swing Chicago Style 120 bpm",
        "author": "bassimat",
        "page": "https://freesound.org/people/bassimat/sounds/853456/",
        "license": "CC0",
        "url": "https://cdn.freesound.org/previews/853/853456_15636277-hq.mp3",
        "bpm": 120,
        "beats_per_bar": 4,
        "start_bar": 8,
        "bars": 8,
    },
]


def fetch(url: str) -> Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / url.rsplit("/", 1)[-1]
    if not dest.exists():
        print(f"downloading {url}")
        subprocess.run(["curl", "-sSL", "--fail", "-o", str(dest), url], check=True)
    return dest


def decode(src: Path) -> np.ndarray:
    """ffmpeg → 44.1 kHz stereo float array (n, 2)."""
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(src), "-f", "s16le",
         "-ar", str(SR), "-ac", "2", "-"],
        check=True, capture_output=True).stdout
    return np.frombuffer(raw, "<i2").astype(np.float64).reshape(-1, 2) / 32767.0


def cut_loop(x: np.ndarray, spec: dict) -> np.ndarray:
    bar = int(round(SR * 60.0 / spec["bpm"] * spec["beats_per_bar"]))
    start = spec["start_bar"] * bar
    end = start + spec["bars"] * bar
    if end > len(x):
        raise SystemExit(f"{spec['title']}: window [{start}:{end}] beyond source ({len(x)})")
    seg = x[start:end].copy()
    # Wrap-crossfade (equal power, 30 ms): what the performance played right
    # after the cut end is blended into the segment head.
    fade = int(0.030 * SR)
    cont = x[end:end + fade]
    fade = min(fade, len(cont))
    theta = np.linspace(0.0, np.pi / 2.0, fade)[:, None]
    seg[:fade] = seg[:fade] * np.sin(theta) + cont[:fade] * np.cos(theta)
    return seg


def encode_ogg(x: np.ndarray) -> bytes:
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes((np.clip(x, -1.0, 1.0) * 32767.0).astype("<i2").tobytes())
    return subprocess.run(
        ["ffmpeg", "-v", "error", "-f", "wav", "-i", "-", "-c:a", "libvorbis",
         "-q:a", "3", "-f", "ogg", "-"],
        check=True, capture_output=True, input=buf.getvalue()).stdout


def main() -> None:
    entries = []
    for spec in LOOPS:
        seg = cut_loop(decode(fetch(spec["url"])), spec)
        ogg = encode_ogg(seg)
        print(f"{spec['title']}: {len(seg) / SR:.1f}s, ogg {len(ogg) / 1024:.0f} kB")
        entries.append((spec, base64.b64encode(ogg).decode("ascii")))
    parts = ["/* Generated by apps/displayer/embed_brush_loops.py — do not edit.",
             " * Embedded recordings and their licenses:"]
    parts.extend(f" *   {s['title']} — {s['author']}, {s['license']}, {s['page']}"
                 for s, _ in entries)
    parts.append(" */")
    parts.append('"use strict";')
    parts.append("window.BRUSH_LOOPS = [")
    for spec, b64 in entries:
        parts.append("  {")
        parts.append(f'    title: "{spec["title"]}",')
        parts.append(f'    author: "{spec["author"]}",')
        parts.append(f'    license: "{spec["license"]}",')
        parts.append(f'    page: "{spec["page"]}",')
        parts.append(f"    bpm: {spec['bpm']},")
        parts.append(f"    beatsPerBar: {spec['beats_per_bar']},")
        parts.append(f"    bars: {spec['bars']},")
        parts.append(f'    ogg: "{b64}",')
        parts.append("  },")
    parts.append("];")
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} kB)")


if __name__ == "__main__":
    main()
